name = "trigger-slate-transcode"
main = "trigger-slate-transcode.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[queues.producers]]
binding = "TRANSCODE_QUEUE"
queue = "transcode-queue"
